spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
    hibernate:
#      ddl-auto: create
  datasource:
    url: jdbc:mysql://atelier.caejnedfdhpl.ap-northeast-2.rds.amazonaws.com/atelier
    username: admin
    password: dltmddusqkqh12
    initialization-mode: always

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

